spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:user-test-db
    username: sa
    password: password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  # default user
  security:
    user:
      name: ${SPRING_DEFAULT_USER_NAME:user}
      password: ${SPRING_DEFAULT_USER_PASSWORD:user}

server:
  port: 8081